export const colorThemes = [
  {
    id: "green",
    name: "Light green",
    hex: "#43A047",
    dark: "#2E7D32",
    soft: "#E8F5E9",
    text: "#1B5E20"
  },
  {
    id: "blue",
    name: "Clinic blue",
    hex: "#2563EB",
    dark: "#1D4ED8",
    soft: "#EFF6FF",
    text: "#1D4ED8"
  },
  {
    id: "teal",
    name: "Calm teal",
    hex: "#0F766E",
    dark: "#115E59",
    soft: "#F0FDFA",
    text: "#115E59"
  },
  {
    id: "slate",
    name: "High contrast",
    hex: "#374151",
    dark: "#111827",
    soft: "#F3F4F6",
    text: "#111827"
  }
];

export const languageOptions = [
  { id: "en", label: "English" },
  { id: "rw", label: "Kinyarwanda" },
  { id: "fr", label: "French" },
  { id: "sw", label: "Kiswahili" }
];

export const translations = {
  en: {
    "app.brand": "Meditrack",
    "app.title": "Appointments",
    "app.online": "Online",
    "app.offlineReady": "Offline ready",
    "app.savedLocally": "Saved locally",
    "app.settings": "Settings",
    "app.account": "Account",
    "app.logout": "Logout",
    "app.login": "Login",
    "app.signup": "Sign up",
    "app.progress": "{percent}% complete",
    "nav.symptoms": "Symptoms",
    "nav.doctors": "Doctors",
    "nav.book": "Book",
    "nav.confirm": "Confirm",
    "nav.visit": "Visit",
    "nav.care": "Care",
    "symptoms.step": "Step 1 of 6",
    "symptoms.title": "What are you feeling today?",
    "symptoms.subtitle": "Choose the closest symptoms. You can add details for the doctor after selecting.",
    "symptoms.alertTitle": "Chest pain can be urgent.",
    "symptoms.alertText": "If pain is severe, spreading, or with shortness of breath, seek emergency care now.",
    "symptoms.select": "Select symptoms",
    "symptoms.selected": "{count} selected",
    "symptoms.notesLabel": "Anything important to add?",
    "symptoms.notesPlaceholder": "Example: symptoms started yesterday evening",
    "symptoms.notesHelp": "Keep it short. This note is saved locally with your appointment.",
    "symptoms.findDoctors": "Find relevant doctors",
    "doctors.step": "Step 2 of 6",
    "doctors.title": "Recommended doctors",
    "doctors.subtitle": "Matches are based on your symptoms, specialty fit, availability, and rating.",
    "doctors.selectedSymptoms": "Your selected symptoms",
    "doctors.bestMatch": "Best match",
    "doctors.available": "Available",
    "doctors.location": "Location",
    "doctors.walkIn": "Walk-in",
    "doctors.choose": "Choose this doctor",
    "doctors.startTitle": "Start with symptoms",
    "doctors.startMessage": "Select one or more symptoms so the app can suggest the most relevant doctors.",
    "booking.step": "Step 3 of 6",
    "booking.title": "Book your appointment",
    "booking.subtitle": "Pick a date and time. Your selection is saved on this device.",
    "booking.date": "Appointment date",
    "booking.timeSlots": "Available time slots",
    "booking.chooseOne": "Choose one",
    "booking.reason": "Reason for visit",
    "booking.reasonPlaceholder": "Example: fever and cough",
    "booking.reasonHelp": "Optional. This helps reception and the doctor prepare.",
    "booking.changeDoctor": "Change doctor",
    "booking.review": "Review appointment",
    "confirmation.step": "Step 4 of 6",
    "confirmation.title": "Confirm your visit",
    "confirmation.subtitle": "Review the details and choose reminder preferences.",
    "confirmation.confirmed": "Confirmed",
    "confirmation.booked": "Appointment {id} is booked",
    "confirmation.saved": "The confirmation is saved on this device for offline access at the hospital.",
    "confirmation.reminders": "Reminders",
    "confirmation.remindersText": "Reminder choices are saved locally and remain available offline.",
    "confirmation.appointmentReminder": "Appointment reminder",
    "confirmation.medicationReminder": "Medication reminder after visit",
    "confirmation.followReminder": "Follow-up reminder",
    "confirmation.edit": "Edit booking",
    "confirmation.confirm": "Confirm appointment",
    "confirmation.checkin": "Continue to check-in",
    "hospital.step": "Step 5 of 6",
    "hospital.title": "Hospital check-in",
    "hospital.subtitle": "Use this screen when you arrive. It works with your saved appointment details.",
    "hospital.arrival": "Arrival guide",
    "hospital.notChecked": "Not checked in",
    "hospital.checked": "Checked in",
    "hospital.checkNow": "Check in now",
    "hospital.liveQueue": "Live queue",
    "hospital.ready": "Ready",
    "hospital.ahead": "{count} ahead of you",
    "hospital.readyText": "Please proceed to consultation",
    "hospital.queueNote": "Updates run automatically while this screen is open. Your current queue status is also saved locally.",
    "hospital.doctorReady": "Your doctor is ready",
    "hospital.afterVisit": "After the consultation, your visit summary and medication reminder plan will be available.",
    "hospital.complete": "Mark visit complete",
    "hospital.viewCare": "View post-visit care",
    "follow.step": "Step 6 of 6",
    "follow.title": "Post-visit care",
    "follow.subtitle": "Your summary, medicine plan, and follow-up reminders are saved locally.",
    "follow.complete": "Visit complete",
    "follow.prescription": "Prescription",
    "follow.followUp": "Follow-up",
    "follow.suggested": "Suggested follow-up date:",
    "follow.settings": "Reminder settings",
    "follow.medTitle": "Medication reminder",
    "follow.medDesc": "Remind me to take medicine on schedule.",
    "follow.followDesc": "Remind me before the follow-up date.",
    "follow.keep": "Keep summary saved",
    "follow.new": "Start new appointment",
    "settings.title": "App settings",
    "settings.subtitle": "Change Meditrack language, color, and local account preferences.",
    "settings.theme": "Color theme",
    "settings.language": "Language",
    "settings.progressTitle": "Appointment progress",
    "settings.accountTitle": "Account",
    "settings.accountText": "Login keeps your local care journey attached to your profile on this device.",
    "account.title": "Account access",
    "account.subtitle": "Login or create a local Meditrack profile for this device.",
    "account.name": "Full name",
    "account.email": "Email",
    "account.password": "Password",
    "account.submitLogin": "Login",
    "account.submitSignup": "Create account",
    "account.switchSignup": "Need an account? Sign up",
    "account.switchLogin": "Already have an account? Login",
    "account.loggedIn": "You are logged in",
    "account.localOnly": "This assessment app stores profile details locally only."
  },
  rw: {
    "app.brand": "Meditrack",
    "app.title": "Gahunda zo kwa muganga",
    "app.online": "Kuri murandasi",
    "app.offlineReady": "Bikora nta murandasi",
    "app.savedLocally": "Byabitswe kuri telefoni",
    "app.settings": "Igenamiterere",
    "app.account": "Konti",
    "app.logout": "Sohoka",
    "app.login": "Injira",
    "app.signup": "Iyandikishe",
    "app.progress": "{percent}% birangiye",
    "nav.symptoms": "Ibimenyetso",
    "nav.doctors": "Abaganga",
    "nav.book": "Gufata",
    "nav.confirm": "Kwemeza",
    "nav.visit": "Kujya",
    "nav.care": "Ubuvuzi",
    "symptoms.step": "Intambwe 1 kuri 6",
    "symptoms.title": "Uyu munsi wumva umeze ute?",
    "symptoms.subtitle": "Hitamo ibimenyetso bikwegereye. Ushobora kongeraho ibisobanuro bigufi.",
    "symptoms.alertTitle": "Ububabare bwo mu gatuza bushobora kwihutirwa.",
    "symptoms.alertText": "Niba bukabije cyangwa bujyanye no guhumeka nabi, shakisha ubuvuzi bwihutirwa.",
    "symptoms.select": "Hitamo ibimenyetso",
    "symptoms.selected": "{count} byatoranyijwe",
    "symptoms.notesLabel": "Hari icyo wongeraho?",
    "symptoms.notesPlaceholder": "Urugero: byatangiye ejo nimugoroba",
    "symptoms.notesHelp": "Andika make. Bibikwa kuri iyi telefoni.",
    "symptoms.findDoctors": "Shaka abaganga bakwiye",
    "doctors.step": "Intambwe 2 kuri 6",
    "doctors.title": "Abaganga bagusabiwe",
    "doctors.subtitle": "Duhitamo dushingiye ku bimenyetso, ubuhanga, igihe, n'amanota.",
    "doctors.selectedSymptoms": "Ibimenyetso wahisemo",
    "doctors.bestMatch": "Uhuye neza",
    "doctors.available": "Arahari",
    "doctors.location": "Aho ari",
    "doctors.walkIn": "Kwinjira",
    "doctors.choose": "Hitamo uyu muganga",
    "doctors.startTitle": "Tangirira ku bimenyetso",
    "doctors.startMessage": "Hitamo ikimenyetso kimwe cyangwa byinshi kugira ngo tubone abaganga bakwiye.",
    "booking.step": "Intambwe 3 kuri 6",
    "booking.title": "Fata gahunda",
    "booking.subtitle": "Hitamo itariki n'isaha. Bizabikwa kuri iki gikoresho.",
    "booking.date": "Itariki ya gahunda",
    "booking.timeSlots": "Amasaha ahari",
    "booking.chooseOne": "Hitamo rimwe",
    "booking.reason": "Impamvu yo gusura",
    "booking.reasonPlaceholder": "Urugero: umuriro n'inkorora",
    "booking.reasonHelp": "Si ngombwa. Bifasha kwakira umurwayi n'umuganga.",
    "booking.changeDoctor": "Hindura umuganga",
    "booking.review": "Reba gahunda",
    "confirmation.step": "Intambwe 4 kuri 6",
    "confirmation.title": "Emeza gahunda",
    "confirmation.subtitle": "Reba amakuru hanyuma uhitemo ukwibutsa.",
    "confirmation.confirmed": "Byemejwe",
    "confirmation.booked": "Gahunda {id} yafashwe",
    "confirmation.saved": "Byabitswe kuri iki gikoresho kugira ngo ubibone nta murandasi.",
    "confirmation.reminders": "Kwibutsa",
    "confirmation.remindersText": "Amahitamo yo kwibutsa abikwa kuri telefoni.",
    "confirmation.appointmentReminder": "Kwibutsa gahunda",
    "confirmation.medicationReminder": "Kwibutsa imiti nyuma yo gusura",
    "confirmation.followReminder": "Kwibutsa gukurikirana",
    "confirmation.edit": "Hindura gahunda",
    "confirmation.confirm": "Emeza gahunda",
    "confirmation.checkin": "Komeza kwiyandikisha",
    "hospital.step": "Intambwe 5 kuri 6",
    "hospital.title": "Kwiyandikisha ku bitaro",
    "hospital.subtitle": "Koresha iyi ecran ugeze ku bitaro.",
    "hospital.arrival": "Uko winjira",
    "hospital.notChecked": "Ntiwiyandikishije",
    "hospital.checked": "Wiyandikishije",
    "hospital.checkNow": "Iyandikishe nonaha",
    "hospital.liveQueue": "Umurongo uriho",
    "hospital.ready": "Witeguye",
    "hospital.ahead": "Hari {count} bakuri imbere",
    "hospital.readyText": "Jya aho muganga agusuzumira",
    "hospital.queueNote": "Amakuru y'umurongo yivugurura ubwayo kandi akabikwa kuri telefoni.",
    "hospital.doctorReady": "Muganga ariteguye",
    "hospital.afterVisit": "Nyuma yo gusuzumwa, uzabona incamake n'ibutsa ry'imiti.",
    "hospital.complete": "Rangiza gusura",
    "hospital.viewCare": "Reba ubuvuzi nyuma",
    "follow.step": "Intambwe 6 kuri 6",
    "follow.title": "Ubuvuzi nyuma yo gusura",
    "follow.subtitle": "Incamake, imiti, n'ibutsa byabitswe kuri telefoni.",
    "follow.complete": "Gusura byarangiye",
    "follow.prescription": "Icyemezo cy'imiti",
    "follow.followUp": "Gukurikirana",
    "follow.suggested": "Itariki yo gukurikirana:",
    "follow.settings": "Igenamiterere ry'ibutsa",
    "follow.medTitle": "Kwibutsa imiti",
    "follow.medDesc": "Unyibutse gufata imiti ku gihe.",
    "follow.followDesc": "Unyibutse mbere y'itariki yo gukurikirana.",
    "follow.keep": "Bika incamake",
    "follow.new": "Fata indi gahunda",
    "settings.title": "Igenamiterere rya porogaramu",
    "settings.subtitle": "Hindura ururimi, ibara, na konti ya Meditrack.",
    "settings.theme": "Ibara",
    "settings.language": "Ururimi",
    "settings.progressTitle": "Aho gahunda igeze",
    "settings.accountTitle": "Konti",
    "settings.accountText": "Kwinjira bihambira urugendo rwawe kuri iyi profayile kuri iki gikoresho.",
    "account.title": "Kwinjira kuri konti",
    "account.subtitle": "Injira cyangwa ukore profayile ya Meditrack kuri iki gikoresho.",
    "account.name": "Amazina yose",
    "account.email": "Imeyili",
    "account.password": "Ijambobanga",
    "account.submitLogin": "Injira",
    "account.submitSignup": "Kora konti",
    "account.switchSignup": "Nta konti ufite? Iyandikishe",
    "account.switchLogin": "Ufite konti? Injira",
    "account.loggedIn": "Winjiye",
    "account.localOnly": "Iyi porogaramu ibika amakuru kuri iki gikoresho gusa."
  },
  fr: {
    "app.brand": "Meditrack",
    "app.title": "Rendez-vous",
    "app.online": "En ligne",
    "app.offlineReady": "Mode hors ligne",
    "app.savedLocally": "Enregistre localement",
    "app.settings": "Parametres",
    "app.account": "Compte",
    "app.logout": "Deconnexion",
    "app.login": "Connexion",
    "app.signup": "Inscription",
    "app.progress": "{percent}% termine",
    "nav.symptoms": "Symptomes",
    "nav.doctors": "Medecins",
    "nav.book": "Reserver",
    "nav.confirm": "Confirmer",
    "nav.visit": "Visite",
    "nav.care": "Soins",
    "symptoms.step": "Etape 1 sur 6",
    "symptoms.title": "Que ressentez-vous aujourd'hui ?",
    "symptoms.subtitle": "Choisissez les symptomes les plus proches. Ajoutez ensuite des details pour le medecin.",
    "symptoms.alertTitle": "Une douleur thoracique peut etre urgente.",
    "symptoms.alertText": "Si la douleur est forte ou accompagnee d'essoufflement, cherchez une aide urgente.",
    "symptoms.select": "Selectionner les symptomes",
    "symptoms.selected": "{count} selectionnes",
    "symptoms.notesLabel": "Quelque chose a ajouter ?",
    "symptoms.notesPlaceholder": "Exemple : les symptomes ont commence hier soir",
    "symptoms.notesHelp": "Restez bref. Cette note est enregistree localement.",
    "symptoms.findDoctors": "Trouver des medecins",
    "doctors.step": "Etape 2 sur 6",
    "doctors.title": "Medecins recommandes",
    "doctors.subtitle": "Les resultats utilisent vos symptomes, la specialite, la disponibilite et la note.",
    "doctors.selectedSymptoms": "Vos symptomes",
    "doctors.bestMatch": "Meilleur choix",
    "doctors.available": "Disponible",
    "doctors.location": "Lieu",
    "doctors.walkIn": "Sans rendez-vous",
    "doctors.choose": "Choisir ce medecin",
    "doctors.startTitle": "Commencez par les symptomes",
    "doctors.startMessage": "Selectionnez un ou plusieurs symptomes pour suggerer les bons medecins.",
    "booking.step": "Etape 3 sur 6",
    "booking.title": "Reserver le rendez-vous",
    "booking.subtitle": "Choisissez une date et une heure. Le choix est enregistre sur cet appareil.",
    "booking.date": "Date du rendez-vous",
    "booking.timeSlots": "Creneaux disponibles",
    "booking.chooseOne": "Choisissez-en un",
    "booking.reason": "Motif de visite",
    "booking.reasonPlaceholder": "Exemple : fievre et toux",
    "booking.reasonHelp": "Optionnel. Cela aide l'accueil et le medecin.",
    "booking.changeDoctor": "Changer de medecin",
    "booking.review": "Verifier",
    "confirmation.step": "Etape 4 sur 6",
    "confirmation.title": "Confirmer la visite",
    "confirmation.subtitle": "Verifiez les details et choisissez les rappels.",
    "confirmation.confirmed": "Confirme",
    "confirmation.booked": "Rendez-vous {id} reserve",
    "confirmation.saved": "La confirmation est enregistree localement pour l'hopital.",
    "confirmation.reminders": "Rappels",
    "confirmation.remindersText": "Les rappels restent disponibles hors ligne.",
    "confirmation.appointmentReminder": "Rappel du rendez-vous",
    "confirmation.medicationReminder": "Rappel medicament apres visite",
    "confirmation.followReminder": "Rappel de suivi",
    "confirmation.edit": "Modifier",
    "confirmation.confirm": "Confirmer",
    "confirmation.checkin": "Aller a l'enregistrement",
    "hospital.step": "Etape 5 sur 6",
    "hospital.title": "Enregistrement a l'hopital",
    "hospital.subtitle": "Utilisez cet ecran a votre arrivee.",
    "hospital.arrival": "Guide d'arrivee",
    "hospital.notChecked": "Pas enregistre",
    "hospital.checked": "Enregistre",
    "hospital.checkNow": "S'enregistrer",
    "hospital.liveQueue": "File en direct",
    "hospital.ready": "Pret",
    "hospital.ahead": "{count} avant vous",
    "hospital.readyText": "Veuillez aller en consultation",
    "hospital.queueNote": "La file se met a jour automatiquement et reste enregistree localement.",
    "hospital.doctorReady": "Votre medecin est pret",
    "hospital.afterVisit": "Apres la consultation, le resume et les rappels seront disponibles.",
    "hospital.complete": "Terminer la visite",
    "hospital.viewCare": "Voir les soins",
    "follow.step": "Etape 6 sur 6",
    "follow.title": "Soins apres visite",
    "follow.subtitle": "Votre resume, traitement et suivi sont enregistres localement.",
    "follow.complete": "Visite terminee",
    "follow.prescription": "Ordonnance",
    "follow.followUp": "Suivi",
    "follow.suggested": "Date de suivi suggeree :",
    "follow.settings": "Parametres de rappel",
    "follow.medTitle": "Rappel medicament",
    "follow.medDesc": "Me rappeler de prendre les medicaments.",
    "follow.followDesc": "Me rappeler avant la date de suivi.",
    "follow.keep": "Garder le resume",
    "follow.new": "Nouveau rendez-vous",
    "settings.title": "Parametres de l'application",
    "settings.subtitle": "Changez la langue, la couleur et le compte Meditrack.",
    "settings.theme": "Couleur",
    "settings.language": "Langue",
    "settings.progressTitle": "Progression",
    "settings.accountTitle": "Compte",
    "settings.accountText": "La connexion garde votre parcours local lie au profil.",
    "account.title": "Acces au compte",
    "account.subtitle": "Connectez-vous ou creez un profil local Meditrack.",
    "account.name": "Nom complet",
    "account.email": "E-mail",
    "account.password": "Mot de passe",
    "account.submitLogin": "Connexion",
    "account.submitSignup": "Creer le compte",
    "account.switchSignup": "Besoin d'un compte ? Inscription",
    "account.switchLogin": "Deja un compte ? Connexion",
    "account.loggedIn": "Vous etes connecte",
    "account.localOnly": "Cette application stocke le profil localement seulement."
  },
  sw: {
    "app.brand": "Meditrack",
    "app.title": "Miadi",
    "app.online": "Mtandaoni",
    "app.offlineReady": "Tayari nje ya mtandao",
    "app.savedLocally": "Imehifadhiwa hapa",
    "app.settings": "Mipangilio",
    "app.account": "Akaunti",
    "app.logout": "Toka",
    "app.login": "Ingia",
    "app.signup": "Jisajili",
    "app.progress": "{percent}% imekamilika",
    "nav.symptoms": "Dalili",
    "nav.doctors": "Madaktari",
    "nav.book": "Weka miadi",
    "nav.confirm": "Thibitisha",
    "nav.visit": "Ziara",
    "nav.care": "Huduma",
    "symptoms.step": "Hatua ya 1 kati ya 6",
    "symptoms.title": "Unajisikiaje leo?",
    "symptoms.subtitle": "Chagua dalili zilizo karibu. Unaweza kuongeza maelezo mafupi.",
    "symptoms.alertTitle": "Maumivu ya kifua yanaweza kuwa dharura.",
    "symptoms.alertText": "Kama maumivu ni makali au una shida kupumua, tafuta huduma ya dharura.",
    "symptoms.select": "Chagua dalili",
    "symptoms.selected": "{count} zimechaguliwa",
    "symptoms.notesLabel": "Kuna jambo muhimu la kuongeza?",
    "symptoms.notesPlaceholder": "Mfano: dalili zilianza jana jioni",
    "symptoms.notesHelp": "Andika kwa kifupi. Maelezo huhifadhiwa hapa.",
    "symptoms.findDoctors": "Tafuta madaktari husika",
    "doctors.step": "Hatua ya 2 kati ya 6",
    "doctors.title": "Madaktari waliopendekezwa",
    "doctors.subtitle": "Matokeo hutegemea dalili, taaluma, upatikanaji, na alama.",
    "doctors.selectedSymptoms": "Dalili ulizochagua",
    "doctors.bestMatch": "Inafaa zaidi",
    "doctors.available": "Anapatikana",
    "doctors.location": "Mahali",
    "doctors.walkIn": "Bila miadi",
    "doctors.choose": "Chagua daktari huyu",
    "doctors.startTitle": "Anza na dalili",
    "doctors.startMessage": "Chagua dalili moja au zaidi ili programu ipendekeze madaktari.",
    "booking.step": "Hatua ya 3 kati ya 6",
    "booking.title": "Weka miadi",
    "booking.subtitle": "Chagua tarehe na muda. Chaguo litahifadhiwa kwenye kifaa hiki.",
    "booking.date": "Tarehe ya miadi",
    "booking.timeSlots": "Muda uliopo",
    "booking.chooseOne": "Chagua moja",
    "booking.reason": "Sababu ya ziara",
    "booking.reasonPlaceholder": "Mfano: homa na kikohozi",
    "booking.reasonHelp": "Si lazima. Husaidia mapokezi na daktari.",
    "booking.changeDoctor": "Badili daktari",
    "booking.review": "Kagua miadi",
    "confirmation.step": "Hatua ya 4 kati ya 6",
    "confirmation.title": "Thibitisha ziara",
    "confirmation.subtitle": "Kagua taarifa na uchague vikumbusho.",
    "confirmation.confirmed": "Imethibitishwa",
    "confirmation.booked": "Miadi {id} imehifadhiwa",
    "confirmation.saved": "Uthibitisho umehifadhiwa hapa kwa matumizi ya hospitali.",
    "confirmation.reminders": "Vikumbusho",
    "confirmation.remindersText": "Vikumbusho huhifadhiwa hapa na hubaki nje ya mtandao.",
    "confirmation.appointmentReminder": "Kikumbusho cha miadi",
    "confirmation.medicationReminder": "Kikumbusho cha dawa baada ya ziara",
    "confirmation.followReminder": "Kikumbusho cha ufuatiliaji",
    "confirmation.edit": "Hariri miadi",
    "confirmation.confirm": "Thibitisha miadi",
    "confirmation.checkin": "Endelea kujisajili",
    "hospital.step": "Hatua ya 5 kati ya 6",
    "hospital.title": "Kujisajili hospitalini",
    "hospital.subtitle": "Tumia skrini hii ukifika hospitalini.",
    "hospital.arrival": "Mwongozo wa kufika",
    "hospital.notChecked": "Hujajisajili",
    "hospital.checked": "Umejisajili",
    "hospital.checkNow": "Jisajili sasa",
    "hospital.liveQueue": "Foleni hai",
    "hospital.ready": "Tayari",
    "hospital.ahead": "{count} mbele yako",
    "hospital.readyText": "Tafadhali nenda kwa daktari",
    "hospital.queueNote": "Foleni hujisasisha yenyewe na huhifadhiwa hapa.",
    "hospital.doctorReady": "Daktari wako yuko tayari",
    "hospital.afterVisit": "Baada ya ziara, muhtasari na vikumbusho vya dawa vitapatikana.",
    "hospital.complete": "Maliza ziara",
    "hospital.viewCare": "Tazama huduma baada ya ziara",
    "follow.step": "Hatua ya 6 kati ya 6",
    "follow.title": "Huduma baada ya ziara",
    "follow.subtitle": "Muhtasari, mpango wa dawa, na vikumbusho vimehifadhiwa hapa.",
    "follow.complete": "Ziara imekamilika",
    "follow.prescription": "Dawa",
    "follow.followUp": "Ufuatiliaji",
    "follow.suggested": "Tarehe ya ufuatiliaji iliyopendekezwa:",
    "follow.settings": "Mipangilio ya vikumbusho",
    "follow.medTitle": "Kikumbusho cha dawa",
    "follow.medDesc": "Nikumbushe kutumia dawa kwa ratiba.",
    "follow.followDesc": "Nikumbushe kabla ya tarehe ya ufuatiliaji.",
    "follow.keep": "Hifadhi muhtasari",
    "follow.new": "Miadi mpya",
    "settings.title": "Mipangilio ya programu",
    "settings.subtitle": "Badili lugha, rangi, na akaunti ya Meditrack.",
    "settings.theme": "Rangi",
    "settings.language": "Lugha",
    "settings.progressTitle": "Maendeleo ya miadi",
    "settings.accountTitle": "Akaunti",
    "settings.accountText": "Kuingia huunganisha safari yako ya huduma na wasifu huu kwenye kifaa.",
    "account.title": "Ufikiaji wa akaunti",
    "account.subtitle": "Ingia au tengeneza wasifu wa Meditrack kwenye kifaa hiki.",
    "account.name": "Jina kamili",
    "account.email": "Barua pepe",
    "account.password": "Nenosiri",
    "account.submitLogin": "Ingia",
    "account.submitSignup": "Tengeneza akaunti",
    "account.switchSignup": "Unahitaji akaunti? Jisajili",
    "account.switchLogin": "Una akaunti? Ingia",
    "account.loggedIn": "Umeingia",
    "account.localOnly": "Programu hii huhifadhi wasifu kwenye kifaa hiki tu."
  }
};

export function getTheme(themeId) {
  return colorThemes.find((theme) => theme.id === themeId) || colorThemes[0];
}

export function translate(language, key, params = {}) {
  const text = translations[language]?.[key] || translations.en[key] || key;

  return Object.entries(params).reduce(
    (value, [paramKey, paramValue]) => value.replaceAll(`{${paramKey}}`, paramValue),
    text
  );
}
